// Code generated by mockery v1.0.0. DO NOT EDIT.

// +build test

package mocks

import mock "github.com/stretchr/testify/mock"
import shared "go-iddd/shared"

// Command is an autogenerated mock type for the Command type
type Command struct {
	mock.Mock
}

// AggregateID provides a mock function with given fields:
func (_m *Command) AggregateID() shared.IdentifiesAggregates {
	ret := _m.Called()

	var r0 shared.IdentifiesAggregates
	if rf, ok := ret.Get(0).(func() shared.IdentifiesAggregates); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shared.IdentifiesAggregates)
		}
	}

	return r0
}

// CommandName provides a mock function with given fields:
func (_m *Command) CommandName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
