// Code generated by mockery v1.0.0. DO NOT EDIT.

// generated from project root with: mockery -name Customer -dir customer/model/ -output customer/application/ -outpkg application

package mocks

import mock "github.com/stretchr/testify/mock"

import shared "go-iddd/shared"

// Customer is an autogenerated mock type for the Customer type
type Customer struct {
	mock.Mock
}

// Apply provides a mock function with given fields: cmd
func (_m *Customer) Apply(cmd shared.Command) error {
	ret := _m.Called(cmd)

	var r0 error
	if rf, ok := ret.Get(0).(func(shared.Command) error); ok {
		r0 = rf(cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
