// Code generated by mockery v1.0.0. DO NOT EDIT.

// generated from project root with: mockery -name Customer -dir customer/model/ -output customer/application/ -outpkg application

package mocks

import mock "github.com/stretchr/testify/mock"
import model "go-iddd/customer/domain"
import valueobject "go-iddd/customer/domain/valueobjects"

// Customers is an autogenerated mock type for the Customers type
type Customers struct {
	mock.Mock
}

// FindBy provides a mock function with given fields: id
func (_m *Customers) FindBy(id valueobject.ID) (model.Customer, error) {
	ret := _m.Called(id)

	var r0 model.Customer
	if rf, ok := ret.Get(0).(func(valueobject.ID) model.Customer); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Customer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(valueobject.ID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: _a0
func (_m *Customers) Save(_a0 model.Customer) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Customer) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
