// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import domain "go-iddd/customer/domain"
import mock "github.com/stretchr/testify/mock"
import values "go-iddd/customer/domain/values"

// Customers is an autogenerated mock type for the Customers type
type Customers struct {
	mock.Mock
}

// Of provides a mock function with given fields: id
func (_m *Customers) Of(id *values.ID) (domain.Customer, error) {
	ret := _m.Called(id)

	var r0 domain.Customer
	if rf, ok := ret.Get(0).(func(*values.ID) domain.Customer); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Customer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*values.ID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: customer
func (_m *Customers) Register(customer domain.Customer) error {
	ret := _m.Called(customer)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Customer) error); ok {
		r0 = rf(customer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
