// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import application "go-iddd/customer/application"
import mock "github.com/stretchr/testify/mock"
import sql "database/sql"

// StartsRepositorySessions is an autogenerated mock type for the StartsRepositorySessions type
type StartsRepositorySessions struct {
	mock.Mock
}

// StartSession provides a mock function with given fields: tx
func (_m *StartsRepositorySessions) StartSession(tx *sql.Tx) application.PersistableCustomers {
	ret := _m.Called(tx)

	var r0 application.PersistableCustomers
	if rf, ok := ret.Get(0).(func(*sql.Tx) application.PersistableCustomers); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(application.PersistableCustomers)
		}
	}

	return r0
}
