// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import application "go-iddd/customer/application"
import mock "github.com/stretchr/testify/mock"

// StartsRepositorySessions is an autogenerated mock type for the StartsRepositorySessions type
type StartsRepositorySessions struct {
	mock.Mock
}

// StartSession provides a mock function with given fields:
func (_m *StartsRepositorySessions) StartSession() (application.PersistableCustomersSession, error) {
	ret := _m.Called()

	var r0 application.PersistableCustomersSession
	if rf, ok := ret.Get(0).(func() application.PersistableCustomersSession); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(application.PersistableCustomersSession)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
