// Code generated by mockery v1.0.0. DO NOT EDIT.

// +build test

package mocked

import es "github.com/AntonStoeckl/go-iddd/service/lib/es"

import mock "github.com/stretchr/testify/mock"
import sql "database/sql"

// ForAssertingUniqueEmailAddresses is an autogenerated mock type for the ForAssertingUniqueEmailAddresses type
type ForAssertingUniqueEmailAddresses struct {
	mock.Mock
}

// Assert provides a mock function with given fields: recordedEvents, tx
func (_m *ForAssertingUniqueEmailAddresses) Assert(recordedEvents es.DomainEvents, tx *sql.Tx) error {
	ret := _m.Called(recordedEvents, tx)

	var r0 error
	if rf, ok := ret.Get(0).(func(es.DomainEvents, *sql.Tx) error); ok {
		r0 = rf(recordedEvents, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
