version: "2"

services:

  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      GOIDDD_USERNAME: goiddd
      GOIDDD_PASSWORD: password123
      GOIDDD_LOCAL_DATABASE: goiddd_local
      GOIDDD_TEST_DATABASE: goiddd_test
    volumes:
      - ./service/customeraccounts/infrastructure/adapter/secondary/postgres/database/setup:/docker-entrypoint-initdb.d
    ports:
      - "15432:5432"