POST http://localhost:8080/v1/customer
Accept: */*
Cache-Control: no-cache

{
  "emailAddress": "anton@stoeckl.de",
  "familyName": "Stöckl",
  "givenName": "Anton"
}

###

GET http://localhost:8080/v1/customer/swagger.json

###