// Code generated by mockery v1.0.0. DO NOT EDIT.

// +build test

package mocks

import (
	lib "go-iddd/service/lib"

	mock "github.com/stretchr/testify/mock"
)

// Command is an autogenerated mock type for the Command type
type Command struct {
	mock.Mock
}

// AggregateID provides a mock function with given fields:
func (_m *Command) AggregateID() lib.IdentifiesAggregates {
	ret := _m.Called()

	var r0 lib.IdentifiesAggregates
	if rf, ok := ret.Get(0).(func() lib.IdentifiesAggregates); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(lib.IdentifiesAggregates)
		}
	}

	return r0
}

// ShouldBeValid provides a mock function with given fields:
func (_m *Command) ShouldBeValid() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
