// Code generated by mockery v1.0.0. DO NOT EDIT.

// +build test

package mocks

import application "go-iddd/service/customer/application"
import mock "github.com/stretchr/testify/mock"
import sql "database/sql"

// StartsCustomersSession is an autogenerated mock type for the StartsCustomersSession type
type StartsCustomersSession struct {
	mock.Mock
}

// StartSession provides a mock function with given fields: tx
func (_m *StartsCustomersSession) StartSession(tx *sql.Tx) application.Customers {
	ret := _m.Called(tx)

	var r0 application.Customers
	if rf, ok := ret.Get(0).(func(*sql.Tx) application.Customers); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(application.Customers)
		}
	}

	return r0
}
