// Code generated by protoc-gen-go. DO NOT EDIT.
// source: customer.proto

package customergrpcproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterRequest struct {
	EmailAddress         string   `protobuf:"bytes,1,opt,name=emailAddress,proto3" json:"emailAddress,omitempty"`
	GivenName            string   `protobuf:"bytes,2,opt,name=givenName,proto3" json:"givenName,omitempty"`
	FamilyName           string   `protobuf:"bytes,3,opt,name=familyName,proto3" json:"familyName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *RegisterRequest) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *RegisterRequest) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

type RegisterResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{1}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ConfirmEmailAddressRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConfirmationHash     string   `protobuf:"bytes,2,opt,name=confirmationHash,proto3" json:"confirmationHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmEmailAddressRequest) Reset()         { *m = ConfirmEmailAddressRequest{} }
func (m *ConfirmEmailAddressRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmEmailAddressRequest) ProtoMessage()    {}
func (*ConfirmEmailAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{2}
}

func (m *ConfirmEmailAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmEmailAddressRequest.Unmarshal(m, b)
}
func (m *ConfirmEmailAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmEmailAddressRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmEmailAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmEmailAddressRequest.Merge(m, src)
}
func (m *ConfirmEmailAddressRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmEmailAddressRequest.Size(m)
}
func (m *ConfirmEmailAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmEmailAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmEmailAddressRequest proto.InternalMessageInfo

func (m *ConfirmEmailAddressRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ConfirmEmailAddressRequest) GetConfirmationHash() string {
	if m != nil {
		return m.ConfirmationHash
	}
	return ""
}

type ChangeEmailAddressRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EmailAddress         string   `protobuf:"bytes,2,opt,name=emailAddress,proto3" json:"emailAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeEmailAddressRequest) Reset()         { *m = ChangeEmailAddressRequest{} }
func (m *ChangeEmailAddressRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeEmailAddressRequest) ProtoMessage()    {}
func (*ChangeEmailAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{3}
}

func (m *ChangeEmailAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeEmailAddressRequest.Unmarshal(m, b)
}
func (m *ChangeEmailAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeEmailAddressRequest.Marshal(b, m, deterministic)
}
func (m *ChangeEmailAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeEmailAddressRequest.Merge(m, src)
}
func (m *ChangeEmailAddressRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeEmailAddressRequest.Size(m)
}
func (m *ChangeEmailAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeEmailAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeEmailAddressRequest proto.InternalMessageInfo

func (m *ChangeEmailAddressRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChangeEmailAddressRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

type ChangeNameRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GivenName            string   `protobuf:"bytes,2,opt,name=givenName,proto3" json:"givenName,omitempty"`
	FamilyName           string   `protobuf:"bytes,3,opt,name=familyName,proto3" json:"familyName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeNameRequest) Reset()         { *m = ChangeNameRequest{} }
func (m *ChangeNameRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeNameRequest) ProtoMessage()    {}
func (*ChangeNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{4}
}

func (m *ChangeNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeNameRequest.Unmarshal(m, b)
}
func (m *ChangeNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeNameRequest.Marshal(b, m, deterministic)
}
func (m *ChangeNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeNameRequest.Merge(m, src)
}
func (m *ChangeNameRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeNameRequest.Size(m)
}
func (m *ChangeNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeNameRequest proto.InternalMessageInfo

func (m *ChangeNameRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChangeNameRequest) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *ChangeNameRequest) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{5}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RetrieveViewRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveViewRequest) Reset()         { *m = RetrieveViewRequest{} }
func (m *RetrieveViewRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveViewRequest) ProtoMessage()    {}
func (*RetrieveViewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{6}
}

func (m *RetrieveViewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveViewRequest.Unmarshal(m, b)
}
func (m *RetrieveViewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveViewRequest.Marshal(b, m, deterministic)
}
func (m *RetrieveViewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveViewRequest.Merge(m, src)
}
func (m *RetrieveViewRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveViewRequest.Size(m)
}
func (m *RetrieveViewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveViewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveViewRequest proto.InternalMessageInfo

func (m *RetrieveViewRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RetrieveViewResponse struct {
	EmailAddress            string   `protobuf:"bytes,1,opt,name=emailAddress,proto3" json:"emailAddress,omitempty"`
	IsEmailAddressConfirmed bool     `protobuf:"varint,2,opt,name=isEmailAddressConfirmed,proto3" json:"isEmailAddressConfirmed,omitempty"`
	GivenName               string   `protobuf:"bytes,3,opt,name=givenName,proto3" json:"givenName,omitempty"`
	FamilyName              string   `protobuf:"bytes,4,opt,name=familyName,proto3" json:"familyName,omitempty"`
	Version                 uint64   `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *RetrieveViewResponse) Reset()         { *m = RetrieveViewResponse{} }
func (m *RetrieveViewResponse) String() string { return proto.CompactTextString(m) }
func (*RetrieveViewResponse) ProtoMessage()    {}
func (*RetrieveViewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{7}
}

func (m *RetrieveViewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveViewResponse.Unmarshal(m, b)
}
func (m *RetrieveViewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveViewResponse.Marshal(b, m, deterministic)
}
func (m *RetrieveViewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveViewResponse.Merge(m, src)
}
func (m *RetrieveViewResponse) XXX_Size() int {
	return xxx_messageInfo_RetrieveViewResponse.Size(m)
}
func (m *RetrieveViewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveViewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveViewResponse proto.InternalMessageInfo

func (m *RetrieveViewResponse) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *RetrieveViewResponse) GetIsEmailAddressConfirmed() bool {
	if m != nil {
		return m.IsEmailAddressConfirmed
	}
	return false
}

func (m *RetrieveViewResponse) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *RetrieveViewResponse) GetFamilyName() string {
	if m != nil {
		return m.FamilyName
	}
	return ""
}

func (m *RetrieveViewResponse) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "customergrpcproto.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "customergrpcproto.RegisterResponse")
	proto.RegisterType((*ConfirmEmailAddressRequest)(nil), "customergrpcproto.ConfirmEmailAddressRequest")
	proto.RegisterType((*ChangeEmailAddressRequest)(nil), "customergrpcproto.ChangeEmailAddressRequest")
	proto.RegisterType((*ChangeNameRequest)(nil), "customergrpcproto.ChangeNameRequest")
	proto.RegisterType((*DeleteRequest)(nil), "customergrpcproto.DeleteRequest")
	proto.RegisterType((*RetrieveViewRequest)(nil), "customergrpcproto.RetrieveViewRequest")
	proto.RegisterType((*RetrieveViewResponse)(nil), "customergrpcproto.RetrieveViewResponse")
}

func init() { proto.RegisterFile("customer.proto", fileDescriptor_9efa92dae3d6ec46) }

var fileDescriptor_9efa92dae3d6ec46 = []byte{
	// 536 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0xdd, 0x0f, 0xd2, 0x51, 0x28, 0xcd, 0x06, 0xb5, 0xa9, 0x5b, 0x95, 0xb0, 0x85, 0x52,
	0x02, 0xd8, 0x2a, 0x5c, 0x10, 0x37, 0x14, 0x2a, 0x71, 0x02, 0xc9, 0x07, 0xc4, 0x85, 0xc3, 0x36,
	0x9e, 0xb8, 0x2b, 0xd9, 0x5e, 0xe3, 0x75, 0x82, 0x0a, 0xe2, 0x82, 0xc4, 0x99, 0x03, 0x7f, 0x8b,
	0x1b, 0x57, 0x8e, 0xfc, 0x10, 0xe4, 0xb5, 0xad, 0x38, 0xb1, 0x37, 0x44, 0xea, 0xd1, 0x33, 0xcf,
	0xf3, 0xde, 0xcc, 0xbe, 0x07, 0xdb, 0xa3, 0x89, 0x4c, 0x45, 0x88, 0x89, 0x1d, 0x27, 0x22, 0x15,
	0xa4, 0x53, 0x7e, 0xfb, 0x49, 0x3c, 0x52, 0x25, 0xeb, 0xc0, 0x17, 0xc2, 0x0f, 0xd0, 0x51, 0x5f,
	0x17, 0x93, 0xb1, 0x83, 0x61, 0x9c, 0x5e, 0xe5, 0x78, 0xeb, 0xb0, 0x68, 0xb2, 0x98, 0x3b, 0x2c,
	0x8a, 0x44, 0xca, 0x52, 0x2e, 0x22, 0x99, 0x77, 0xa9, 0x84, 0x5b, 0x2e, 0xfa, 0x5c, 0xa6, 0x98,
	0xb8, 0xf8, 0x71, 0x82, 0x32, 0x25, 0x14, 0xda, 0x18, 0x32, 0x1e, 0xbc, 0xf4, 0xbc, 0x04, 0xa5,
	0xec, 0x19, 0x7d, 0xe3, 0x74, 0xcb, 0x9d, 0xab, 0x91, 0x43, 0xd8, 0xf2, 0xf9, 0x14, 0xa3, 0x37,
	0x2c, 0xc4, 0x9e, 0xa9, 0x00, 0xb3, 0x02, 0x39, 0x02, 0x18, 0xb3, 0x90, 0x07, 0x57, 0xaa, 0xbd,
	0xa6, 0xda, 0x95, 0x0a, 0xa5, 0xb0, 0x33, 0x23, 0x95, 0xb1, 0x88, 0x24, 0x92, 0x6d, 0x30, 0xb9,
	0x57, 0x70, 0x99, 0xdc, 0xa3, 0xef, 0xc1, 0x1a, 0x8a, 0x68, 0xcc, 0x93, 0xf0, 0xbc, 0x42, 0x5c,
	0x6a, 0x5c, 0x40, 0x93, 0x01, 0xec, 0x8c, 0x72, 0xb4, 0xda, 0xee, 0x35, 0x93, 0x97, 0x85, 0xac,
	0x5a, 0x9d, 0xbe, 0x85, 0xfd, 0xe1, 0x25, 0x8b, 0x7c, 0x5c, 0x65, 0xf0, 0xe2, 0x31, 0xcc, 0xfa,
	0x31, 0x28, 0x83, 0x4e, 0x3e, 0x30, 0x5b, 0x4e, 0x37, 0xe8, 0x7a, 0x17, 0xbb, 0x03, 0x37, 0x5f,
	0x61, 0x80, 0xa9, 0x6e, 0x3c, 0xbd, 0x0f, 0x5d, 0x17, 0xd3, 0x84, 0xe3, 0x14, 0xdf, 0x71, 0xfc,
	0xa4, 0x83, 0xfd, 0x32, 0xe0, 0xf6, 0x3c, 0xae, 0x38, 0xff, 0x2a, 0x8f, 0xfe, 0x1c, 0xf6, 0xb8,
	0xac, 0x1e, 0xad, 0x78, 0x20, 0xf4, 0xd4, 0x42, 0x2d, 0x57, 0xd7, 0x9e, 0x5f, 0x7e, 0x6d, 0xf9,
	0xf2, 0xeb, 0x8b, 0xcb, 0x93, 0x1e, 0xdc, 0x98, 0x62, 0x22, 0xb9, 0x88, 0x7a, 0x1b, 0x7d, 0xe3,
	0x74, 0xdd, 0x2d, 0x3f, 0x9f, 0xfe, 0xd9, 0x80, 0xd6, 0xb0, 0x88, 0x03, 0x09, 0xa0, 0x55, 0xba,
	0x8a, 0x50, 0xbb, 0x96, 0x12, 0x7b, 0xc1, 0xe7, 0xd6, 0xf1, 0x52, 0x4c, 0x7e, 0x17, 0xba, 0xf7,
	0xed, 0xf7, 0xdf, 0x9f, 0x66, 0x87, 0xb6, 0x9d, 0xe9, 0x99, 0x53, 0xe2, 0x5f, 0x18, 0x03, 0xf2,
	0xc3, 0x80, 0x6e, 0x83, 0x41, 0xc9, 0x93, 0x86, 0xa9, 0x7a, 0x23, 0x5b, 0xbb, 0x76, 0x1e, 0x4f,
	0xbb, 0xcc, 0xae, 0x7d, 0x9e, 0x65, 0x97, 0x9e, 0x29, 0xde, 0x47, 0xd6, 0x49, 0x95, 0xd7, 0xf9,
	0xc2, 0xbd, 0xaf, 0x8e, 0x7a, 0x13, 0x96, 0x8f, 0x71, 0x0a, 0x77, 0x67, 0x8a, 0xbe, 0x1b, 0x40,
	0xea, 0xc6, 0x26, 0x8f, 0x9b, 0x04, 0xe9, 0xfc, 0xaf, 0xd5, 0xf3, 0x50, 0xe9, 0x39, 0xb6, 0x8e,
	0x96, 0xeb, 0xc9, 0x74, 0x84, 0x00, 0xb3, 0x38, 0x90, 0x7b, 0x5a, 0xfa, 0x4a, 0x5a, 0xb4, 0xb4,
	0x77, 0x15, 0xed, 0x81, 0xb5, 0x5b, 0xa7, 0x8d, 0x58, 0x88, 0x19, 0xdd, 0x07, 0xd8, 0xcc, 0xa3,
	0x41, 0xfa, 0x0d, 0x54, 0x73, 0xa9, 0xd1, 0xd2, 0xec, 0x2b, 0x9a, 0xee, 0xa0, 0x53, 0xa3, 0x21,
	0x9f, 0xa1, 0x5d, 0x0d, 0x0c, 0x39, 0x69, 0x74, 0x4d, 0x2d, 0x79, 0xd6, 0x83, 0xff, 0xe2, 0x0a,
	0x87, 0x15, 0xdc, 0xa4, 0xce, 0x7d, 0xb1, 0xa9, 0x7e, 0x7b, 0xf6, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0xef, 0x84, 0x5e, 0x9d, 0x03, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomerClient is the client API for Customer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomerClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	ConfirmEmailAddress(ctx context.Context, in *ConfirmEmailAddressRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ChangeEmailAddress(ctx context.Context, in *ChangeEmailAddressRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ChangeName(ctx context.Context, in *ChangeNameRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	RetrieveView(ctx context.Context, in *RetrieveViewRequest, opts ...grpc.CallOption) (*RetrieveViewResponse, error)
}

type customerClient struct {
	cc *grpc.ClientConn
}

func NewCustomerClient(cc *grpc.ClientConn) CustomerClient {
	return &customerClient{cc}
}

func (c *customerClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/customergrpcproto.Customer/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) ConfirmEmailAddress(ctx context.Context, in *ConfirmEmailAddressRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/customergrpcproto.Customer/ConfirmEmailAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) ChangeEmailAddress(ctx context.Context, in *ChangeEmailAddressRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/customergrpcproto.Customer/ChangeEmailAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) ChangeName(ctx context.Context, in *ChangeNameRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/customergrpcproto.Customer/ChangeName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/customergrpcproto.Customer/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) RetrieveView(ctx context.Context, in *RetrieveViewRequest, opts ...grpc.CallOption) (*RetrieveViewResponse, error) {
	out := new(RetrieveViewResponse)
	err := c.cc.Invoke(ctx, "/customergrpcproto.Customer/RetrieveView", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerServer is the server API for Customer service.
type CustomerServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	ConfirmEmailAddress(context.Context, *ConfirmEmailAddressRequest) (*empty.Empty, error)
	ChangeEmailAddress(context.Context, *ChangeEmailAddressRequest) (*empty.Empty, error)
	ChangeName(context.Context, *ChangeNameRequest) (*empty.Empty, error)
	Delete(context.Context, *DeleteRequest) (*empty.Empty, error)
	RetrieveView(context.Context, *RetrieveViewRequest) (*RetrieveViewResponse, error)
}

// UnimplementedCustomerServer can be embedded to have forward compatible implementations.
type UnimplementedCustomerServer struct {
}

func (*UnimplementedCustomerServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedCustomerServer) ConfirmEmailAddress(ctx context.Context, req *ConfirmEmailAddressRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmEmailAddress not implemented")
}
func (*UnimplementedCustomerServer) ChangeEmailAddress(ctx context.Context, req *ChangeEmailAddressRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeEmailAddress not implemented")
}
func (*UnimplementedCustomerServer) ChangeName(ctx context.Context, req *ChangeNameRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeName not implemented")
}
func (*UnimplementedCustomerServer) Delete(ctx context.Context, req *DeleteRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedCustomerServer) RetrieveView(ctx context.Context, req *RetrieveViewRequest) (*RetrieveViewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveView not implemented")
}

func RegisterCustomerServer(s *grpc.Server, srv CustomerServer) {
	s.RegisterService(&_Customer_serviceDesc, srv)
}

func _Customer_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customergrpcproto.Customer/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_ConfirmEmailAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmEmailAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).ConfirmEmailAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customergrpcproto.Customer/ConfirmEmailAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).ConfirmEmailAddress(ctx, req.(*ConfirmEmailAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_ChangeEmailAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeEmailAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).ChangeEmailAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customergrpcproto.Customer/ChangeEmailAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).ChangeEmailAddress(ctx, req.(*ChangeEmailAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_ChangeName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).ChangeName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customergrpcproto.Customer/ChangeName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).ChangeName(ctx, req.(*ChangeNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customergrpcproto.Customer/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_RetrieveView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).RetrieveView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customergrpcproto.Customer/RetrieveView",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).RetrieveView(ctx, req.(*RetrieveViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Customer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "customergrpcproto.Customer",
	HandlerType: (*CustomerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Customer_Register_Handler,
		},
		{
			MethodName: "ConfirmEmailAddress",
			Handler:    _Customer_ConfirmEmailAddress_Handler,
		},
		{
			MethodName: "ChangeEmailAddress",
			Handler:    _Customer_ChangeEmailAddress_Handler,
		},
		{
			MethodName: "ChangeName",
			Handler:    _Customer_ChangeName_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Customer_Delete_Handler,
		},
		{
			MethodName: "RetrieveView",
			Handler:    _Customer_RetrieveView_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "customer.proto",
}
