// Code generated by generate/main.go. DO NOT EDIT.

package commands_test

import (
	"go-iddd/customer/domain/commands"
	"go-iddd/customer/domain/values"
	"go-iddd/shared"
	"testing"

	"github.com/cockroachdb/errors"
	. "github.com/smartystreets/goconvey/convey"
)

func TestNewChangeEmailAddress(t *testing.T) {
	Convey("Given valid input", t, func() {
		customerID := "64bcf656-da30-4f5a-b0b5-aead60965aa3"
		emailAddress := "john@doe.com"

		Convey("When a new ChangeEmailAddress command is created", func() {
			changeEmailAddress, err := commands.NewChangeEmailAddress(customerID, emailAddress)

			Convey("It should succeed", func() {
				So(err, ShouldBeNil)
				So(changeEmailAddress, ShouldHaveSameTypeAs, (*commands.ChangeEmailAddress)(nil))
			})
		})

		Convey("Given that customerID is invalid", func() {
			customerID = ""
			conveyNewChangeEmailAddressWithInvalidInput(customerID, emailAddress)
		})

		Convey("Given that emailAddress is invalid", func() {
			emailAddress = ""
			conveyNewChangeEmailAddressWithInvalidInput(customerID, emailAddress)
		})
	})
}

func conveyNewChangeEmailAddressWithInvalidInput(
	customerID string,
	emailAddress string,
) {

	Convey("When a new ChangeEmailAddress command is created", func() {
		changeEmailAddress, err := commands.NewChangeEmailAddress(customerID, emailAddress)

		Convey("It should fail", func() {
			So(err, ShouldBeError)
			So(errors.Is(err, shared.ErrInputIsInvalid), ShouldBeTrue)
			So(changeEmailAddress, ShouldBeNil)
		})
	})
}

func TestChangeEmailAddressExposesExpectedValues(t *testing.T) {
	Convey("Given a ChangeEmailAddress command", t, func() {
		customerID := "64bcf656-da30-4f5a-b0b5-aead60965aa3"
		emailAddress := "john@doe.com"

		customerIDValue, err := values.CustomerIDFrom(customerID)
		So(err, ShouldBeNil)
		emailAddressValue, err := values.EmailAddressFrom(emailAddress)
		So(err, ShouldBeNil)

		changeEmailAddress, err := commands.NewChangeEmailAddress(customerID, emailAddress)
		So(err, ShouldBeNil)

		Convey("It should expose the expected values", func() {
			So(customerIDValue.Equals(changeEmailAddress.CustomerID()), ShouldBeTrue)
			So(emailAddressValue.Equals(changeEmailAddress.EmailAddress()), ShouldBeTrue)
			So(changeEmailAddress.CommandName(), ShouldEqual, "ChangeEmailAddress")
			So(customerIDValue.Equals(changeEmailAddress.AggregateID()), ShouldBeTrue)
		})
	})
}
