// Code generated by mockery v1.0.0. DO NOT EDIT.

// +build test

package mocked

import es "github.com/AntonStoeckl/go-iddd/service/lib/es"
import mock "github.com/stretchr/testify/mock"

// EventStore is an autogenerated mock type for the EventStore type
type EventStore struct {
	mock.Mock
}

// AppendEventsToStream provides a mock function with given fields: streamID, events
func (_m *EventStore) AppendEventsToStream(streamID es.StreamID, events es.DomainEvents) error {
	ret := _m.Called(streamID, events)

	var r0 error
	if rf, ok := ret.Get(0).(func(es.StreamID, es.DomainEvents) error); ok {
		r0 = rf(streamID, events)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoadEventStream provides a mock function with given fields: streamID, fromVersion, maxEvents
func (_m *EventStore) LoadEventStream(streamID es.StreamID, fromVersion uint, maxEvents uint) (es.DomainEvents, error) {
	ret := _m.Called(streamID, fromVersion, maxEvents)

	var r0 es.DomainEvents
	if rf, ok := ret.Get(0).(func(es.StreamID, uint, uint) es.DomainEvents); ok {
		r0 = rf(streamID, fromVersion, maxEvents)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(es.DomainEvents)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(es.StreamID, uint, uint) error); ok {
		r1 = rf(streamID, fromVersion, maxEvents)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PurgeEventStream provides a mock function with given fields: streamID
func (_m *EventStore) PurgeEventStream(streamID es.StreamID) error {
	ret := _m.Called(streamID)

	var r0 error
	if rf, ok := ret.Get(0).(func(es.StreamID) error); ok {
		r0 = rf(streamID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
