POST http://localhost:8080/v1/customer
Accept: */*
Cache-Control: no-cache

{
  "emailAddress": "anton@stoeckl.de",
  "familyName": "Stöckl",
  "givenName": "Anton"
}

###

PUT http://localhost:8080/v1/customer/37823c13-e357-43d6-a7a3-e90ad08cb899/emailaddress/confirm
Accept: */*
Cache-Control: no-cache

{
  "emailAddress": "anton@stoeckl.de",
  "confirmationHash": "30dfece0ffc90e4f402fbfec1b1b7d85"
}

###

PUT http://localhost:8080/v1/customer/37823c13-e357-43d6-a7a3-e90ad08cb899/emailaddress
Accept: */*
Cache-Control: no-cache

{
  "emailAddress": "anton+changed@stoeckl.de"
}

###

GET http://localhost:8080/v1/customer/swagger.json

###