// Code generated by generate/main.go. DO NOT EDIT.

package events_test

import (
	"go-iddd/customer/domain/events"
	"go-iddd/customer/domain/values"
	"go-iddd/shared"
	"testing"
	"time"

	"github.com/cockroachdb/errors"
	. "github.com/smartystreets/goconvey/convey"
)

func TestItWasRegistered(t *testing.T) {
	Convey("Given valid parameters as input", t, func() {
		customerID := values.GenerateCustomerID()
		emailAddress, err := values.EmailAddressFrom("foo@bar.com")
		So(err, ShouldBeNil)
		confirmableEmailAddress := emailAddress.ToConfirmable()
		personName, err := values.PersonNameFrom("John", "Doe")
		So(err, ShouldBeNil)

		Convey("When a new Registered event is created", func() {
			streamVersion := uint(1)
			registered := events.ItWasRegistered(customerID, confirmableEmailAddress, personName, streamVersion)

			Convey("It should succeed", func() {
				So(registered, ShouldNotBeNil)
				So(registered, ShouldImplement, (*shared.DomainEvent)(nil))
				So(registered, ShouldHaveSameTypeAs, (*events.Registered)(nil))
			})
		})
	})
}

func TestRegisteredExposesExpectedValues(t *testing.T) {
	Convey("Given a Registered event", t, func() {
		customerID := values.GenerateCustomerID()
		emailAddress, err := values.EmailAddressFrom("foo@bar.com")
		So(err, ShouldBeNil)
		confirmableEmailAddress := emailAddress.ToConfirmable()
		personName, err := values.PersonNameFrom("John", "Doe")
		So(err, ShouldBeNil)
		streamVersion := uint(1)

		beforeItOccurred := time.Now()
		registered := events.ItWasRegistered(customerID, confirmableEmailAddress, personName, streamVersion)
		afterItOccurred := time.Now()

		Convey("It should expose the expected values", func() {
			So(registered.CustomerID(), ShouldResemble, customerID)
			So(registered.ConfirmableEmailAddress(), ShouldResemble, confirmableEmailAddress)
			So(registered.PersonName(), ShouldResemble, personName)
			So(registered.Identifier(), ShouldEqual, customerID.String())
			So(registered.EventName(), ShouldEqual, "CustomerRegistered")
			itOccurred, err := time.Parse(events.RegisteredMetaTimestampFormat, registered.OccurredAt())
			So(err, ShouldBeNil)
			So(beforeItOccurred, ShouldHappenBefore, itOccurred)
			So(afterItOccurred, ShouldHappenAfter, itOccurred)
			So(registered.StreamVersion(), ShouldEqual, streamVersion)
		})
	})
}

func TestRegisteredMarshalJSON(t *testing.T) {
	Convey("Given a Registered event", t, func() {
		customerID := values.GenerateCustomerID()
		emailAddress, err := values.EmailAddressFrom("foo@bar.com")
		So(err, ShouldBeNil)
		confirmableEmailAddress := emailAddress.ToConfirmable()
		personName, err := values.PersonNameFrom("John", "Doe")
		So(err, ShouldBeNil)
		streamVersion := uint(1)

		registered := events.ItWasRegistered(customerID, confirmableEmailAddress, personName, streamVersion)

		Convey("When it is marshaled to json", func() {
			data, err := registered.MarshalJSON()

			Convey("It should create the expected json", func() {
				So(err, ShouldBeNil)
				So(string(data), ShouldStartWith, "{")
				So(string(data), ShouldEndWith, "}")
			})
		})
	})
}

func TestRegisteredUnmarshalJSON(t *testing.T) {
	Convey("Given a Registered event marshaled to json", t, func() {
		customerID := values.GenerateCustomerID()
		emailAddress, err := values.EmailAddressFrom("foo@bar.com")
		So(err, ShouldBeNil)
		confirmableEmailAddress := emailAddress.ToConfirmable()
		personName, err := values.PersonNameFrom("John", "Doe")
		So(err, ShouldBeNil)
		streamVersion := uint(1)

		registered := events.ItWasRegistered(customerID, confirmableEmailAddress, personName, streamVersion)

		data, err := registered.MarshalJSON()
		So(err, ShouldBeNil)

		Convey("When it is unmarshaled", func() {
			unmarshaled := &events.Registered{}
			err := unmarshaled.UnmarshalJSON(data)

			Convey("It should be equal to the original Registered event", func() {
				So(err, ShouldBeNil)
				So(registered, ShouldResemble, unmarshaled)
			})
		})
	})

	Convey("Given invalid json", t, func() {
		data := []byte("666")

		Convey("When it is unmarshaled to Registered event", func() {
			unmarshaled := &events.Registered{}
			err := unmarshaled.UnmarshalJSON(data)

			Convey("It should fail", func() {
				So(err, ShouldNotBeNil)
				So(errors.Is(err, shared.ErrUnmarshalingFailed), ShouldBeTrue)
			})
		})
	})
}
