#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE $GOIDDD_DATABASE;
    CREATE USER $GOIDDD_USERNAME WITH PASSWORD '$GOIDDD_PASSWORD';
    GRANT ALL privileges ON DATABASE $GOIDDD_DATABASE to $GOIDDD_USERNAME;
EOSQL
