#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $GOIDDD_USERNAME WITH PASSWORD '$GOIDDD_PASSWORD';

    CREATE DATABASE $GOIDDD_DATABASE;
    GRANT ALL privileges ON DATABASE $GOIDDD_DATABASE to $GOIDDD_USERNAME;

    CREATE DATABASE $GOIDDD_DATABASE_TEST;
    GRANT ALL privileges ON DATABASE $GOIDDD_DATABASE_TEST to $GOIDDD_USERNAME;
EOSQL
