// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import shared "go-iddd/shared"

// Customer is an autogenerated mock type for the Customer type
type Customer struct {
	mock.Mock
}

// AggregateID provides a mock function with given fields:
func (_m *Customer) AggregateID() shared.AggregateID {
	ret := _m.Called()

	var r0 shared.AggregateID
	if rf, ok := ret.Get(0).(func() shared.AggregateID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shared.AggregateID)
		}
	}

	return r0
}

// AggregateName provides a mock function with given fields:
func (_m *Customer) AggregateName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Apply provides a mock function with given fields: cmd
func (_m *Customer) Apply(cmd shared.Command) error {
	ret := _m.Called(cmd)

	var r0 error
	if rf, ok := ret.Get(0).(func(shared.Command) error); ok {
		r0 = rf(cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RecordedEvents provides a mock function with given fields:
func (_m *Customer) RecordedEvents() shared.DomainEvents {
	ret := _m.Called()

	var r0 shared.DomainEvents
	if rf, ok := ret.Get(0).(func() shared.DomainEvents); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shared.DomainEvents)
		}
	}

	return r0
}
