// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import shared "go-iddd/shared"

// EventStore is an autogenerated mock type for the EventStore type
type EventStore struct {
	mock.Mock
}

// AppendToStream provides a mock function with given fields: events
func (_m *EventStore) AppendToStream(events shared.DomainEvents) error {
	ret := _m.Called(events)

	var r0 error
	if rf, ok := ret.Get(0).(func(shared.DomainEvents) error); ok {
		r0 = rf(events)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoadEventStream provides a mock function with given fields: identifier
func (_m *EventStore) LoadEventStream(identifier shared.IdentifiesAggregates) (shared.DomainEvents, error) {
	ret := _m.Called(identifier)

	var r0 shared.DomainEvents
	if rf, ok := ret.Get(0).(func(shared.IdentifiesAggregates) shared.DomainEvents); ok {
		r0 = rf(identifier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shared.DomainEvents)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(shared.IdentifiesAggregates) error); ok {
		r1 = rf(identifier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadPartialEventStream provides a mock function with given fields: identifier, fromVersion, maxEvents
func (_m *EventStore) LoadPartialEventStream(identifier shared.IdentifiesAggregates, fromVersion uint, maxEvents uint) (shared.DomainEvents, error) {
	ret := _m.Called(identifier, fromVersion, maxEvents)

	var r0 shared.DomainEvents
	if rf, ok := ret.Get(0).(func(shared.IdentifiesAggregates, uint, uint) shared.DomainEvents); ok {
		r0 = rf(identifier, fromVersion, maxEvents)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shared.DomainEvents)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(shared.IdentifiesAggregates, uint, uint) error); ok {
		r1 = rf(identifier, fromVersion, maxEvents)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
